### ISSUE TITLE
ansible-doc thycotic_secret returns error

### ISSUE THREAD

**Issue by bschonec** [thycotic/secret-server-ansible-lookup-plugin#5]
Even though the secret-server-sdk-client and the thycotic_secret.py are installed correctly, there doesn't appear to be any ansible documentation:

[user@example]$ ansible-doc thycotic_secret
ERROR! module thycotic_secret has a documentation error formatting or is missing documentation.

**Comment by perzizzle** [comment]
The documentation isn't valid.

`
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 268, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 382, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 584, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 539, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/usr/lib/python2.7/site-packages/jinja2/runtime.py", line 193, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 687, in _lookup
    instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 563, in get
    self._load_config_defs(name, self._module_cache[path], path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 293, in _load_config_defs
    dstring = AnsibleLoader(getattr(module, 'DOCUMENTATION', ''), file_name=path).get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8040)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8295)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10544)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:10722)
ScannerError: mapping values are not allowed in this context
  in "<byte string>", line 3, column 15
`
